# Generated by Django 4.2.8 on 2023-12-22 12:41

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_category_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='products/default.jpg', upload_to=products.models.upload_to, verbose_name='Image'),
        ),
    ]
